export const COST_MAX_DATE_RANGE_DAYS = 90;
export const COST_MAX_SERVICE_ROWS = 25;
export const LOGS_MAX_HOURS = 24;
export const LOGS_MAX_EVENTS = 50;
export const LOGS_MAX_MESSAGE_LENGTH = 1_000;
export const LOGS_MAX_LOOKBACK_MINUTES = 1_440;
export const LOGS_DEFAULT_LOOKBACK_MINUTES = 30;
export const LOGS_MAX_FILTER_PATTERN_LENGTH = 256;
export const LOG_STREAM_PREFIX_MAX_LENGTH = 512;

export const EC2_CACHE_TTL_SECONDS = 300;
export const CW_CACHE_TTL_SECONDS = 300;
export const CW_MAX_ALARMS = 100;
export const CW_ALARM_PREFIX_MAX_LENGTH = 256;
export const CW_ALARM_REASON_MAX_LENGTH = 500;
export const LOGS_CACHE_TTL_SECONDS = 300;

export const LAMBDA_MAX_FUNCTIONS = 100;
export const LAMBDA_CACHE_TTL_SECONDS = 300;
export const S3_MAX_BUCKETS = 100;
export const S3_CACHE_TTL_SECONDS = 300;
export const LOG_GROUPS_MAX_COUNT = 100;
export const LOG_GROUP_PREFIX_MAX_LENGTH = 256;

export const ECS_MAX_TASKS = 100;
export const ECS_MAX_SERVICE_EVENTS = 10;
export const ECS_MAX_LOOKBACK_MINUTES = 1440;
export const ECS_CACHE_TTL_SECONDS = 300;

export const OVERVIEW_SAMPLE_LIMIT = 5;
export const OVERVIEW_DEFAULT_SERVICE_LIMIT = 10;
