export const COST_MAX_DATE_RANGE_DAYS = 90;
export const COST_MAX_SERVICE_ROWS = 25;
export const LOGS_MAX_HOURS = 24;
export const LOGS_MAX_EVENTS = 50;
export const LOGS_MAX_MESSAGE_LENGTH = 1_000;
export const LOGS_MAX_LOOKBACK_MINUTES = 1_440;
export const LOGS_DEFAULT_LOOKBACK_MINUTES = 30;
export const LOGS_MAX_FILTER_PATTERN_LENGTH = 256;
export const LOG_STREAM_PREFIX_MAX_LENGTH = 512;

export const EC2_CACHE_TTL_SECONDS = 300;
export const CW_CACHE_TTL_SECONDS = 300;
export const CW_MAX_ALARMS = 100;
export const CW_ALARM_PREFIX_MAX_LENGTH = 256;
export const CW_ALARM_REASON_MAX_LENGTH = 500;
export const LOGS_CACHE_TTL_SECONDS = 300;

export const LAMBDA_MAX_FUNCTIONS = 100;
export const LAMBDA_CACHE_TTL_SECONDS = 300;
export const S3_MAX_BUCKETS = 100;
export const S3_CACHE_TTL_SECONDS = 300;
export const LOG_GROUPS_MAX_COUNT = 100;
export const LOG_GROUP_PREFIX_MAX_LENGTH = 256;

export const ECS_MAX_TASKS = 100;
export const ECS_MAX_SERVICE_EVENTS = 10;
export const ECS_MAX_LOOKBACK_MINUTES = 1440;
export const ECS_CACHE_TTL_SECONDS = 300;

export const RDS_CACHE_TTL_SECONDS = 300;
export const RDS_DB_INSTANCE_ID_MAX_LENGTH = 63;
export const RDS_MAX_LOOKBACK_MINUTES = 1440;
export const RDS_DEFAULT_LOOKBACK_MINUTES = 60;
export const RDS_MIN_PERIOD_SECONDS = 60;
export const RDS_MAX_PERIOD_SECONDS = 3600;
export const RDS_DEFAULT_PERIOD_SECONDS = 300;
export const RDS_MAX_METRIC_DATAPOINTS = 60;

export const SSM_CACHE_TTL_SECONDS = 300;
export const SSM_PARAMETER_PREFIX_MAX_LENGTH = 512;
export const SSM_MAX_REQUIRED_PARAMETER_NAMES = 50;
export const SSM_PARAMETER_NAME_MAX_LENGTH = 256;
export const SSM_MAX_DESCRIBE_RESULTS = 500;

export const ECR_CACHE_TTL_SECONDS = 300;
export const ECR_REPOSITORY_NAME_MAX_LENGTH = 256;
export const ECR_IMAGE_TAG_MAX_LENGTH = 128;
export const ECR_IMAGE_DIGEST_MAX_LENGTH = 80;

export const ECS_IMAGE_COMPARE_MAX_TASKS = 5;

export const S3_BUCKET_NAME_MAX_LENGTH = 63;
export const S3_BUCKET_POSTURE_CACHE_TTL_SECONDS = 300;
export const S3_MAX_LIFECYCLE_RULES_SUMMARY = 20;
export const S3_METRIC_LOOKBACK_MINUTES = 1440;
export const S3_METRIC_PERIOD_SECONDS = 86400;

export const OVERVIEW_SAMPLE_LIMIT = 5;
export const OVERVIEW_DEFAULT_SERVICE_LIMIT = 10;
